component_depth: 1
languages:
- java
exclude:
- ./config/.*
- ./contrib/.*
- ./contrib/bcel/.*
- ./contrib/bcel/docs/.*
- ./contrib/examples/.*
- ./contrib/examples/XInclude/.*
- ./contrib/examples/checks/.*
- ./contrib/examples/checks/com/.*
- ./contrib/examples/checks/com/mycompany/.*
- ./contrib/examples/checks/com/mycompany/checks/.*
- ./contrib/examples/checks/com/puppycrawl/.*
- ./contrib/examples/checks/com/puppycrawl/tools/.*
- ./contrib/examples/checks/com/puppycrawl/tools/checkstyle/.*
- ./contrib/examples/checks/com/puppycrawl/tools/checkstyle/checks/.*
- ./contrib/examples/checks/com/puppycrawl/tools/checkstyle/checks/xpath/.*
- ./contrib/examples/conf/.*
- ./contrib/examples/filters/.*
- ./contrib/examples/filters/com/.*
- ./contrib/examples/filters/com/mycompany/.*
- ./contrib/examples/filters/com/mycompany/filters/.*
- ./contrib/examples/listeners/.*
- ./contrib/examples/listeners/com/.*
- ./contrib/examples/listeners/com/mycompany/.*
- ./contrib/examples/listeners/com/mycompany/listeners/.*
- ./contrib/hooks/.*
- ./contrib/usage/.*
- ./lib/.*
- ./target/.*
- ./target/classes/.*
- ./target/classes/com/.*
- ./target/classes/com/puppycrawl/.*
- ./target/classes/com/puppycrawl/tools/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/api/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/annotation/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/blocks/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/coding/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/design/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/duplicates/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/header/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/imports/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/indentation/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/javadoc/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/metrics/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/modifier/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/naming/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/regexp/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/sizes/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/checks/whitespace/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/doclets/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/filters/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/grammars/.*
- ./target/classes/com/puppycrawl/tools/checkstyle/gui/.*
- ./target/test-classes/.*
- ./target/test-classes/com/.*
- ./target/test-classes/com/puppycrawl/.*
- ./target/test-classes/com/puppycrawl/tools/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/api/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/annotation/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/blocks/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/coding/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/design/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/duplicates/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/header/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/imports/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/indentation/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/javadoc/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/metrics/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/modifier/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/naming/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/regexp/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/sizes/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/checks/whitespace/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/filters/.*
- ./target/test-classes/com/puppycrawl/tools/checkstyle/grammars/.*
